### ISSUE TITLE
Solution to stderr stdout

### ISSUE THREAD

**Issue by dstegelman** [divisible-by-hero/tailor#1]
We can turn em off!

http://docs.fabfile.org/en/1.4.0/usage/output_controls.html#hiding-and-or-showing-output-levels

**Comment by gpennington** [comment]
That's good.  Can we still collect the output to return to the browser?  Or does it just turn off output to stdout?

**Comment by dstegelman** [comment]
While I haven't tested yet, the docs appear to say that there is an output dictionary with true, false values.  We can still capture the output, just not send it to sterr or stdout.

**Comment by dstegelman** [comment]
Woot DONE!
